# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b033ae0da7acf372be387b7ab2382672d429950a49fda617b15be1aa3b6daa62bd34df602669ee0b95711929005b2ff924da9b0ad3bc3cab93ad3db844821b5b

test:
  secret_key_base: a07f4d1d35aa8917903b24893c5e3bc2e8a07395702488b842a81ef246b15c15ae4626361bbd3bb92fb192483a31f360d70a644bf26a1b1a8c2c8491970b2755

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
